# Generated by Django 5.0.2 on 2024-03-25 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=2000, verbose_name='Titre')),
                ('objectif', models.TextField(verbose_name='Objectfs')),
                ('duree', models.CharField(max_length=50, verbose_name='Durée')),
                ('tarif', models.IntegerField(verbose_name='Tarif par heure')),
                ('prerequis', models.TextField(verbose_name='Prerequis')),
                ('public', models.TextField(verbose_name='Public visé')),
                ('programme', models.TextField(verbose_name='Programmes')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.categorie', verbose_name='Catégorie')),
            ],
        ),
    ]
