# Generated by Django 5.0.2 on 2024-03-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='programme',
        ),
    ]
